const data = [
  {
    id: "1",
    title: "BeerSource",
    description: "Website",
    builtWith: ["react", "react-router", "javascript", "html", "css", "mapbox"],
    url: "https://beersource.netlify.app/",
    thumbnail: "beersource.png",
    learnings: "learned alot",
  },
  {
    id: "2",
    title: "All The Views",
    description: "Website",
    builtWith: [
      "react",
      "react-router",
      "javascript",
      "html",
      "css",
      "styled-components",
    ],
    url: "https://all-the-views.netlify.app/",
    thumbnail: "alltheviews.png",
    learnings: "learned alot",
  },
  {
    id: "3",
    title: "Wallpaper Finder",
    description: "Website",
    builtWith: ["react", "javascript", "html", "css"],
    url: "https://minimal-wallpaper-finder.netlify.app/",
    thumbnail: "wallpaperfinder.png",
    learnings: "learned alot",
  },
  {
    id: "4",
    title: "Sushi Master",
    description: "Website",
    builtWith: ["react", "javascript", "html", "css", "styled-components"],
    url: "https://master-of-sushi.netlify.app/",
    thumbnail: "sushimaster.png",
    learnings: "learned alot",
  },
  {
    id: "5",
    title: "BookShelf",
    description: "Website",
    builtWith: [
      "javascript",
      "html",
      "css",
      "mongoDB",
      "EJS Templating",
      "node.js",
      "express.js",
    ],
    url: "https://evening-shore-85582.herokuapp.com/",
    thumbnail: "bookshelf.png",
    learnings: "learned alot",
  },
];

export default data;
