const data = [
  {
    id: "1",
    title: "BeerSource",
    description: "Find local breweries or brew your own with recipes",
    builtWith: ["react", "react-router", "javascript", "html", "css", "mapbox"],
    url: "https://beersource.herokuapp.com/",
    thumbnail: "beersource.png",
    learnings: "learned alot",
    repo: "https://github.com/a-stepanian/beersource",
  },
  {
    id: "2",
    title: "All The Views",
    description: "Discover the hidden gems of the PNW",
    builtWith: [
      "react",
      "react-router",
      "javascript",
      "html",
      "css",
      "styled-components",
    ],
    url: "https://all-the-views.netlify.app/",
    thumbnail: "alltheviews.png",
    learnings: "learned alot",
    repo: "https://github.com/a-stepanian/all-the-views",
  },
  {
    id: "3",
    title: "Wallpaper Finder",
    description: "Search for high quality wallpapers for your device",
    builtWith: ["react", "javascript", "html", "css"],
    url: "https://minimal-wallpaper-finder.netlify.app/",
    thumbnail: "wallpaperfinder.png",
    learnings: "learned alot",
    repo: "https://github.com/a-stepanian/wallpaper-finder",
  },
  // {
  //   id: "4",
  //   title: "Sushi Master",
  //   description: "Restaurant website",
  //   builtWith: ["react", "javascript", "html", "css", "styled-components"],
  //   url: "https://master-of-sushi.netlify.app/",
  //   thumbnail: "sushimaster.png",
  //   learnings: "learned alot",
  //   repo: "https://github.com/a-stepanian/sushi-master",
  // },
  {
    id: "5",
    title: "BookWorm",
    description:
      "Full stack CRUD application to join a club, add books, and leave reviews.",
    builtWith: [
      "javascript",
      "html",
      "css",
      "mongoDB",
      "EJS Templating",
      "node.js",
      "express.js",
    ],
    url: "https://evening-shore-85582.herokuapp.com/",
    thumbnail: "bookshelf.png",
    learnings: "learned alot",
    repo: "https://github.com/a-stepanian/BookShelf",
  },
];

export default data;

export const experience = [
  {
    company: "United States Gypsum Company",
    location: "Rainier, OR",
    title: "Engineering and Mill Manager",
    date: "2020 - 2021",
    description: [
      "Manage the safety, development, productivity and engagement of 36 employees comprised of PLC Programmers, electricians, engineers, and other plant staff.",
      "Define and implement the long-term capital strategy of the plant and execute over $4MM in project work.",
      "Evaluate improvement efforts to improve profitability of the facility and grow the business.",
    ],
  },
  {
    company: "United States Gypsum Company",
    location: "Chamblee, GA",
    title: "Engineering, Production, and Supply Chain Manager",
    date: "2017 - 2020",
    description: [
      "Managed the safety, development, productivity and engagement of 27 employees.",
      "Ran trials and reformulated Dry Joint compound products to save over $300,000 annually.",
      "Increased Dry Joint efficiency 5% YTD in 2020 over 2019 by keeping employees focused and engaged.",
      "Strategically reduced annual maintenance material spending by 41% ($174,000) in 2018.",
      "Reduced energy consumption by 35%, saving the facility $90,000 annually.",
      "Installed new automation equipment to improve safety and reduce Sherwin Williams product delay by 24%.",
    ],
  },
  {
    company: "United States Gypsum Company",
    location: "Baltimore, MD",
    title: "Reliability and Project Engineer",
    date: "2013 - 2017",
    description: [
      "Lead numerous reliability and process improvement projects throughout the plant.",
      "Facilitated efficiency improvement projects and trained associates to lead their own projects.",
      "Conducted training and mentored employees on problem solving techniques.",
      "Oversaw the equipment reliability and maintenance program for a multi-departmental production facility.",
      "Planned and executed multiple concurrent capital investment projects on time and under budget.",
    ],
  },
];
